name: "Compile the homework"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.3.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: "Install the packages"
        run: julia --project -e 'import Pkg; Pkg.instantiate()'
      - name: "Make index page"
        run: cp README.md dist/index.md
      - name: "Build the demonstration"
        run: julia --project -e 'using Weave; weave(joinpath("homework", "00_demonstration.Jmd"); doctype="github", out_path="dist")'
      - name: "HOMEWORK 01"
        run: julia --project -e 'using Weave; weave(joinpath("homework", "01_bifurcation.Jmd"); doctype="github", out_path="dist")'
      - name: "HOMEWORK 02"
        run: julia --project -e 'using Weave; weave(joinpath("homework", "02_logistic.Jmd"); doctype="github", out_path="dist")'
      - name: "HOMEWORK 03"
        run: julia --project -e 'using Weave; weave(joinpath("homework", "03_competition.Jmd"); doctype="github", out_path="dist")'
      - name: "HOMEWORK 04"
        run: julia --project -e 'using Weave; weave(joinpath("homework", "04_stability.Jmd"); doctype="github", out_path="dist")'
      - name: "HOMEWORK 05"
        run: julia --project -e 'using Weave; weave(joinpath("homework", "05_sd1.Jmd"); doctype="github", out_path="dist")'
      - name: "HOMEWORK 06"
        run: julia --project -e 'using Weave; weave(joinpath("homework", "06_eia.Jmd"); doctype="github", out_path="dist")'
      - name: "GitHub Pages deployment"
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: "dist/"
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
